### ISSUE TITLE
Service Workers behaviour could be confusing

### ISSUE THREAD

**Issue by paullewis** [GoogleChrome/application-shell#24]
Since we don't declare to the dev that they are running a SW they might think something is broken.

Suggestions:
1. A traffic light overlay that tells a developer that they're serving from SW or not
2. Changed content from initial load ("this is done over network; future loads will be from SW" vs "I'm coming from the SW, you will need to Cmd+Shift+R to load over the network")

**Comment by addyosmani** [comment]
I'd personally favor the second option. Any preferences, @gauntface?

**Comment by gauntface** [comment]
Toast would be my preference.

Option 1: Not possible because of sw-precache
Option 2: Easy to do, but requires logic that I wouldn't really expect to live in production environment when the developer gets familiar with SW.

Alternatives:
- The index partial has explanation and it's displayed regardless of coming from SW or not.
- Make a controller that is served up with the index partial that will add the logic to display whether a SW is controlling the page (Assuming that is possible without message the SW etc).

**Comment by addyosmani** [comment]
If we don't mind still opting for the toast pattern then Toast +1.

**Comment by jeffposnick** [comment]
There's some code in the `sw-precache` demo that you could reuse to show an appropriate toast, via hooking into SW lifecycle methods: https://github.com/GoogleChrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js#L33

I'm not sure why the "traffic light overlay" would be impossible due to `sw-precache`. It should be possible to implemented that via JS in the controlled page that hung off the `navigator.serviceWorker.ready` promise (start at red, move to green if/when the promise resolved). If I have a vote, I'd go with toasts rather than a traffic light, though.

**Comment by gauntface** [comment]
Added toast.
