### ISSUE TITLE
Add support for sw-precache to the build

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/application-shell#4]
Unless there's a good reason not to. If there is a good reason not to, I'd like to try to address it in the library.

As it stands, the SW implementation will end up trying to re-fetch all the static resources each time the version is bumped, and there's no cache-busting URL parameter to protect against stale resources being returned from the HTTP cache during the `install` phase.

Depending on what the HTTP cache expiration is for the static resources, you'll either end up making unnecessary network requests (if your cache expiration is very short) or risk serving stale content from your service worker's `fetch` handler (if your cache expiration is longer).

`sw-precache` will version each resource automatically and only re-fetch those that change, appending a cache-busting URL parameter.

**Comment by addyosmani** [comment]
Good question!. The initial reason for not using `sw-precache` for this project was attempting to keep the architecture vanilla and not as heavily reliant on build-time tooling. This enables the flexibility to explain the shell architecture without making assumptions that a build step is going to be involved or possible. That said, you're completely correct about the re-fetching issue and we could be a lot smarter with out approach to cache busting.

If we opt for `sw-precache` here, I think we should make using it either a core or optional part of the appshell + content documentation we ship so that we're consistent with how we present the approach. Any interest in a PR that adds in `sw-precache` here? :)

@tjsavage do you have any thoughts on Jeff's comments above? I'm personally fine with us adding this in given that we already have a build process in this repo (and most of the other canonical apps already share a similar setup).

**Comment by addyosmani** [comment]
sw-precache support is probably the next item we'll want to tackle. I think once we've landed support for it, @robdodson (Polymer and c/o) should have a rough reference point they can follow for their progressive app.

**Comment by jeffposnick** [comment]
:+1: I'd imagine that getting the [`dynamicUrlToDependencies`](https://github.com/GoogleChrome/sw-precache#dynamicurltodependencies-objectstringarraystring) settings correct and using [`navigateFallback`](https://github.com/GoogleChrome/sw-precache#navigatefallback-string) might be the trickiest parts of migrating over to `sw-precache`, so please ping me if the documentation is unclear.

https://github.com/GoogleChrome/sw-precache/blob/app-shell-demo/app-shell-demo/gulpfile.babel.js#L92 might help as a reference.

**Comment by addyosmani** [comment]
We now have an implementation of this in master. I've already reviewed, but it might be useful to get @jeffposnick's eyes on it too in case there's further improvements we can make.

**Comment by jeffposnick** [comment]
https://github.com/addyosmani/app-shell/blob/deabdc15701dfebb64d8c9158a45d00f5e97a013/gulp-tasks/service-worker.js#L30 gets a :+1: to me. Apologies that there were some rough spots getting the initial integration set up.

My only comment is that `swPrecache.write()` returns a promise now, so you can do away with the `cb` and just use the promise as the return value for the `gulp` task. Not that it changes anything functionally, but it "looks" nicer.

**Comment by gauntface** [comment]
PR including the promise change in the works.
